### ISSUE TITLE
feature request: add github action to create pypi on release creation

### ISSUE THREAD

**Issue by shimwell** [aidancrilly/NeSST#10]
Automating the pypi release process can be done with a github action if that helps save some human time.

happy to contribute an action that does a pypi release triggered by a github release if you like.

I would just make a yaml file for this smf the PyPi account owner would need to add the NeSST repo as a [trusted publisher](https://docs.pypi.org/trusted-publishers/adding-a-publisher/)

```
name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
```
